numToCreate = 1000;
numToDelete = 500;

varsCreated = [];

vars = {}

builtinNames = [
"x",
"y",
"xprevious",
"yprevious",
"xstart",
"ystart",
"hspeed",
"vspeed",
"direction",
"speed",
"friction",
"gravity",
"gravity_direction",
"in_collision_tree",
"object_index",
"id",
"alarm",
"solid",
"visible",
"persistent",
"managed",
"depth",
"bbox_left", 
"bbox_right", 
"bbox_top", 
"bbox_bottom", 
"sprite_index", 
"image_index", 
"image_single", 
"image_number", 
"sprite_width", 
"sprite_height", 
"sprite_xoffset", 
"sprite_yoffset", 
"image_xscale", 
"image_yscale", 
"image_angle", 
"image_alpha", 
"image_blend", 
"image_speed", 
"mask_index", 
"path_index", 
"path_position", 
"path_positionprevious", 
"path_speed", 
"path_scale", 
"path_orientation", 
"path_endaction", 
"timeline_index", 
"timeline_position", 
"timeline_speed", 
"timeline_running", 
"timeline_loop", 

"phy_rotation", 
"phy_position_x", 
"phy_position_y", 
"phy_angular_velocity", 
"phy_linear_velocity_x", 
"phy_linear_velocity_y", 
"phy_speed_x", 
"phy_speed_y", 
"phy_speed", 
"phy_angular_damping", 
"phy_linear_damping", 
"phy_bullet", 
"phy_fixed_rotation", 
"phy_active", 

"phy_mass", 
"phy_inertia", 
"phy_com_x", 
"phy_com_y", 
"phy_dynamic", 
"phy_kinematic", 
"phy_sleeping", 
"phy_position_xprevious", 
"phy_position_yprevious", 
"layer", 
"in_sequence", 
"sequence_instance", 
"drawn_by_sequence", 

]

call_later(5, time_source_units_seconds, function(){
	olympus_test_resolve();
})