name: Build the project and run Olympus test suites
run-name: Testing runtime ${{ inputs.runtime }}

on:
  push:
    paths-ignore:
      - "**.md"
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Target runtime'
        required: false
      runner:
        description: 'Runner'
        required: false
        default: "ubuntu-latest"
      platform:
        description: 'Platform'
        required: false
  workflow_call:
    inputs:
      runtime:
        description: 'Target runtime'
        required: false
        type: string
      runner:
        description: 'Runner'
        required: false
        type: string
      platform:
        description: 'Platform'
        required: false
        type: string
permissions:
  contents: write

env:
  MATRIX_STRING: '[\"windows-latest\",\"ubuntu-latest\", \"macOS-latest\"]'
  RAW_TEST_RESULT_FILE_NAME: 'ganary.raw.olympus.json'
  TEST_RESULT_FILE_NAME: 'result.json'

jobs:
  # By default, this workflow will run on Windows, Ubuntu, and MacOS runners, making and testing the Windows, Android, and iOS builds. However, this job checks for the manual input of `runner` to override the default, so we can manually run the workflow on a specific runner instead of all three.
  runner:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - if: ${{ inputs.runner }}
      run: echo "MATRIX_STRING=[\\\"${{ github.event.inputs.runner }}\\\"]" >> $GITHUB_ENV
    - id: set-matrix
      run: echo "matrix=${{ env.MATRIX_STRING }}" >> $GITHUB_OUTPUT

  test:
    needs: runner
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.runner.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      #region Get the version from the yyp file
      - name: Get the version from the yyp file for Linux
        if: runner.os == 'Linux'
        run: |
          echo "YYP_VERSION=$(grep -oP '(?<=IDEVersion":")(\d+\.\d+\.\d+\.\d+)(?=")' ${{ github.workspace }}/Ganary/Ganary Blah.yyp)" >> $GITHUB_ENV
      - name: Get the version from the yyp file for MacOS
        if: runner.os == 'macOS'
        run: |
          echo "YYP_VERSION=$(egrep -o 'IDEVersion":"([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)' ${GITHUB_WORKSPACE}/Ganary/Ganary Blah.yyp | cut -d '"' -f 3)" >> $GITHUB_ENV
      - name: Get the version from the yyp file for Windows
        if: runner.os == 'Windows'
        run: |
          $yypVersion = Select-String -Path "${env:GITHUB_WORKSPACE}\Ganary\Ganary Blah.yyp" -Pattern 'IDEVersion":"(\d+\.\d+\.\d+\.\d+)' -AllMatches | ForEach-Object { $_.Matches.Groups[1].Value }
          "YYP_VERSION=$yypVersion" | Out-File -Append -FilePath $env:GITHUB_ENV 
      #endregion
      #region Android setup
      - name: Create the keystore file from secrets
        id: write_file
        if: runner.os == 'Linux'
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'myTemporaryFile.keystore'
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Create the local-settings-override-file for igor-setup
        if: runner.os == 'Linux'
        run: |
          echo "{
            \"machine.Platform Settings.Android.Keystore.filename\": \"${{ steps.write_file.outputs.filePath }}\",
            \"machine.Platform Settings.Android.Keystore.keystore_password\": \"${{ secrets.KEYSTORE_PASSWORD }}\",
            \"machine.Platform Settings.Android.Keystore.keystore_alias_password\": \"${{ secrets.KEYSTORE_PASSWORD }}\",
            \"machine.Platform Settings.Android.Keystore.alias\": \"${{ secrets.KEYSTORE_USERNAME }}\",
            \"machine.Platform Settings.Android.Paths.jdk_location\": \"$JAVA_HOME_17_X64\"
          }" > local_settings.json
      - name: Set up ffmpeg # This step may be removed when https://github.com/YoYoGames/GameMaker-Bugs/issues/4977 is fixed
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: '6.1.0'
        if: runner.os == 'Linux'
      - name: Set Up Android SDK's platform-tools # The default Android SDK does not include platform-tools and its component `adb`, which is required by Igor for the Android build
        if: runner.os == 'Linux'
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools"
      #endregion
      - name: use Igor Setup
        uses: bscotch/igor-setup@v1
        with:
          access-key: ${{ secrets.ACCESS_KEY }}
          target-yyp: ${{ github.workspace }}/Ganary/Ganary Blah.yyp
          local-settings-override-file: ${{ github.workspace }}/local_settings.json
          runtime-version: ${{ inputs.runtime }}
          cache: true
          modules: ${{inputs.platform}}
        id: igor
      - name: use Igor build
        uses: bscotch/igor-build@v1.0.4
        id: build
        timeout-minutes: 30
        with:
          yyp-path: ${{ github.workspace }}/Ganary/Ganary Blah.yyp
          user-dir: ${{ steps.igor.outputs.user-dir }}
          platform: ${{inputs.platform}}
      # region Build for iOS through Fastlane
