name: Continuous Integration for Windows export

on:
  # push:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - id: find_yyp
        name: Find the yyp file
        run: |
          $yyp = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter *.yyp
          Write-Output "YYP file found at: $yyp"
          echo "yyp-path=$yyp" >> $GITHUB_OUTPUT
      - name: use Igor Setup
        uses: bscotch/igor-setup@v1
        with:
          access-key: ${{ secrets.ACCESS_KEY }}
          target-yyp: ${{ steps.find_yyp.outputs.yyp-path }}
        id: igor
      - name: use Igor build
        uses: bscotch/igor-build@v1
        id: build
        timeout-minutes: 30
        with:
          yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
          user-dir: ${{ steps.igor.outputs.user-dir }}
      - name: upload-build
        uses: actions/upload-artifact@v4
        with:
          name: igor-build-windows
          path: ${{ steps.build.outputs.out-dir }}
          retention-days: 1